// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Bio struct {
	ID      string  `json:"id"`
	User    *User   `json:"user,omitempty"`
	Content *string `json:"content,omitempty"`
}

type Mutation struct {
}

type NewTodo struct {
	Text   string `json:"text"`
	UserID string `json:"userId"`
}

type Profile struct {
	ID       string  `json:"id"`
	User     *User   `json:"user,omitempty"`
	Headline *string `json:"headline,omitempty"`
	Location *string `json:"location,omitempty"`
}

type Query struct {
}

type Todo struct {
	ID   string `json:"id"`
	Text string `json:"text"`
	Done bool   `json:"done"`
	User *User  `json:"user"`
}

type User struct {
	ID             string   `json:"id"`
	Email          string   `json:"email"`
	FirstName      *string  `json:"firstName,omitempty"`
	LastName       *string  `json:"lastName,omitempty"`
	ProfilePicture *string  `json:"profilePicture,omitempty"`
	Bio            *Bio     `json:"bio,omitempty"`
	Profile        *Profile `json:"profile,omitempty"`
}
